---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04


suites:
  - name: hello 
    run_list:
      - recipe[hello::hello]
    attributes:
